from django.conf import settings
from django.urls import path
from . import views

BASE_URL = settings.BASE_URL.strip("/")

urlpatterns = [
    path(f'{BASE_URL}/',                           views.home_view,               name='home'),
    path(f'{BASE_URL}/upload/',                    views.upload_file_view,        name='upload_file'),
    path(f'{BASE_URL}/define-columns/',            views.define_columns_view,     name='define_columns'),
    path(f'{BASE_URL}/tagging/',                   views.tagging_view,            name='tagging'),
    path(f'{BASE_URL}/tagging/progress/',          views.tagging_progress_view,   name='tagging_progress'),
    path(f'{BASE_URL}/tagging/pause/',             views.pause_tagging_view,      name='pause_tagging'),
    path(f'{BASE_URL}/tagging/resume/',            views.resume_tagging_view,     name='resume_tagging'),
    path(f'{BASE_URL}/tagging/image-status/',      views.tagging_image_status_view, name='tagging_image_status'),
    path(f'{BASE_URL}/tagging/llm-status/',        views.tagging_llm_status_view, name='tagging_llm_status'),
    path(f'{BASE_URL}/tagging/stop/',              views.stop_tagging_view,       name='stop_tagging'),
    path(f'{BASE_URL}/llm_status/',                views.llm_status_view,         name='llm_status'),
    path(f'{BASE_URL}/results/',                   views.results_view,            name='results'),
    path(f'{BASE_URL}/connection/',                views.connection_editor_view,  name='connection_editor'),
    path(f'{BASE_URL}/connection/test/',           views.test_connection_view,    name='test_connection'),
    path(f'{BASE_URL}/image-backend/',             views.image_backend_view,          name='image_backend'),
    path(f'{BASE_URL}/image-backend/capability/',  views.image_capability_view,       name='image_capability'),
    path(f'{BASE_URL}/image-backend/models/',      views.image_models_view,           name='image_models'),
    path(f'{BASE_URL}/image-backend/loras/',       views.image_loras_view,            name='image_loras'),
    path(f'{BASE_URL}/image-backend/download/',    views.image_download_view,         name='image_download'),
    path(f'{BASE_URL}/image-backend/download/status/', views.image_download_status_view, name='image_download_status'),
    path(f'{BASE_URL}/image-backend/compare/',     views.compare_models_view,         name='compare_models'),
    path(f'{BASE_URL}/image_status/',              views.image_status_view,           name='image_status'),
    path(f'{BASE_URL}/define-columns/estimate/',   views.estimate_image_view,         name='estimate_image'),
    path(f'{BASE_URL}/define-columns/build-reference-index/', views.build_reference_index_view,  name='build_reference_index'),
    path(f'{BASE_URL}/define-columns/reference-index-status/', views.reference_index_status_view, name='reference_index_status'),
    path(f'{BASE_URL}/define-columns/add-reference-files/', views.add_reference_files_view,  name='add_reference_files'),
    path(f'{BASE_URL}/define-columns/remove-reference-file/', views.remove_reference_file_view, name='remove_reference_file'),
    path(f'{BASE_URL}/results/regenerate/',        views.regenerate_image_view,       name='regenerate_image'),
    path(f'{BASE_URL}/results/select-image/',      views.select_image_view,           name='select_image'),
    path(f'{BASE_URL}/results/review/',            views.set_review_view,             name='set_review'),
    path(f'{BASE_URL}/results/bulk-retry/',        views.bulk_retry_view,             name='bulk_retry'),
    path(f'{BASE_URL}/results/bulk-retry/status/', views.bulk_retry_status_view,      name='bulk_retry_status'),
    path(f'{BASE_URL}/gallery/',                          views.gallery_view,               name='gallery_all'),
    path(f'{BASE_URL}/gallery/retry/',                    views.gallery_retry_view,         name='gallery_retry'),
    path(f'{BASE_URL}/gallery/retry/status/',             views.gallery_retry_status_view,  name='gallery_retry_status'),
    path(f'{BASE_URL}/gallery/zip/',                      views.gallery_zip_view,           name='gallery_zip'),
    path(f'{BASE_URL}/project/<str:project_id>/gallery/', views.gallery_view,               name='project_gallery'),
    path(f'{BASE_URL}/project/<str:project_id>/open/',   views.project_open_view,   name='project_open'),
    path(f'{BASE_URL}/project/<str:project_id>/delete/', views.delete_project_view, name='project_delete'),
]
